<div class="zdt-toolbar-entry">
    <div class="zdt-toolbar-preview">
        <img  src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAWBJREFUeNpiYBg04P////ZAXA9l8wNxPhD7A7E+Qc1v+MX/w8BHr4D/fx4+gnD27/////37/7+aW/9/4BFCwSA9cAM+SCv9xwDx8f//gxzDzw+h0TDIEJBepp+79ubzP7mL6qQPHxgYHjxgYIiPZ2DYsIGB4f59BgZ9TJ+8FpC0Z/ja3vP/14MH/79dvPQfLwB6BeSqb0zM/1+xcv5/z8H7/y2f6H+GT5Hx/98Vl/0/aeOOVd+jaXPAGAbeHT72/2JU8v93LOwQb4CIX4yMYIFfCYkoNr5zdv9/j4MPjD85uQLjqB6MfxkYgvXADYA5C2zIgYMQA86fBwfWJ2ZWsDgyBqkF6QHpZQEFxg8mFobL3CLggFE8fpZB0d6OgcHAgOGQnDbDn0+fsEa94ZdXDEygWPjLxMzwm42TgZvhPxh/WraK4d/Hj2BFYjYWcHF0DNKDL1X2g5IRKDUwDH8AEGAAtLlNHkCc0REAAAAASUVORK5CYII=" alt="CouchDB (DoctrineCouchODMModule)">
        <span class="zdt-toolbar-info">
            <?php echo $this->collector->getQueryCount(); ?> queries
        </span>
    </div>
    <div class="zdt-toolbar-detail">
        <span class="zdt-toolbar-info zdt-toolbar-info-heading">Details</span>
        <span class="zdt-toolbar-info">
            <span class="zdt-detail-label">Help us!</span>
            <span class="zdt-detail-value zdt-detail-value-right">
                Please help us improve
                <br/>
                profiling by forking and
                <br/>
                contributing to
                <br/>
                <a href="https://github.com/doctrine/DoctrineCouchODMModule/fork_select" target="_blank">
                    DoctrineCouchODMModule
                </a>
            </span>
        </span>

        <span class="zdt-toolbar-info zdt-toolbar-info-heading">Queries <span class="ddt-toolbar-info">for <?php echo $this->collector->getName() ?></span></span>
        <span class="zdt-toolbar-info ddt-toolbar-info">
        <?php foreach ($this->collector->getQueries() as $query): ?>
            <hr/>

            <?php if (isset($query['db'])): ?>
                <span class="zdt-detail-label">Database</span>
                <span class="zdt-detail-value ddt-detail-value">
                    <?php \Doctrine\Common\Util\Debug::dump($query['db']) ?>
                </span>
                <span class="clear"></span>
            <?php endif ?>

            <?php if (isset($query['collection'])): ?>
                <span class="zdt-detail-label">Collection</span>
                <span class="zdt-detail-value ddt-detail-value">
                    <?php \Doctrine\Common\Util\Debug::dump($query['collection']) ?>
                </span>
                <span class="clear"></span>
            <?php endif ?>

            <span class="zdt-detail-label">Query</span>
            <span class="zdt-detail-value ddt-detail-query ddt-detail-value">

                <?php if (isset($query['query']) && is_array($query['query']) && !empty($query['query'])): ?>
                    <?php foreach($query['query'] as $key => $value): ?>
                        <?php print_r($value) ?>
                    <?php endforeach ?>
                <?php endif ?>
            </span>

            <span class="clear"></span>

            <?php if (isset($query['fields']) && is_array($query['fields']) && !empty($query['fields'])): ?>
                <span class="zdt-detail-label">Fields</span>
                <span class="zdt-detail-value ddt-detail-value">
                        <?php foreach($query['fields'] as $key => $value): ?>
                            &nbsp;&nbsp;&nbsp;&nbsp;<?php echo $key ?> => <?php print_r($value) ?>
                        <?php endforeach ?>
                </span>
                <span class="clear"></span>
            <?php endif ?>

            <?php if (isset($query['find'])): ?>
                <span class="zdt-detail-label">Find</span>
                <span class="zdt-detail-value ddt-detail-value">
                    <?php \Doctrine\Common\Util\Debug::dump($query['find']) ?>
                </span>
                <span class="clear"></span>
            <?php endif ?>

            <?php if (isset($query['limit'])): ?>
                <span class="zdt-detail-label">Limit to</span>
                <span class="zdt-detail-value ddt-detail-value">
                    <?php \Doctrine\Common\Util\Debug::dump($query['limitNum']) ?>
                </span>
                <span class="clear"></span>
            <?php endif ?>

            <?php if (isset($query['sort'])): ?>
                <span class="zdt-detail-label">Sort by</span>
                <span class="zdt-detail-value ddt-detail-value">
                    <?php \Doctrine\Common\Util\Debug::dump($query['sortFields']) ?>
                </span>
                <span class="clear"></span>
            <?php endif ?>

            <?php if (isset($query['skip'])): ?>
                <span class="zdt-detail-label">Skip to</span>
                <span class="zdt-detail-value ddt-detail-value">
                    <?php \Doctrine\Common\Util\Debug::dump($query['skipNum']) ?>
                </span>
                <span class="clear"></span>
            <?php endif ?>

            <?php if (isset($query['authenticate'])): ?>
                <span class="zdt-detail-label">Authenticate</span>
                <span class="zdt-detail-value ddt-detail-value">
                    &nbsp;&nbsp;&nbsp;&nbsp;username => <?php \Doctrine\Common\Util\Debug::dump($query['username']) ?><br/>
                    &nbsp;&nbsp;&nbsp;&nbsp;password => <?php \Doctrine\Common\Util\Debug::dump($query['password']) ?>
                </span>
                <span class="clear"></span>
            <?php endif ?>

            <?php if (isset($query['command'])): ?>
                <span class="zdt-detail-label">Command</span>
                <span class="zdt-detail-value ddt-detail-value">
                    &nbsp;&nbsp;&nbsp;&nbsp;data => <?php \Doctrine\Common\Util\Debug::dump($query['data']) ?><br/>
                    &nbsp;&nbsp;&nbsp;&nbsp;options => <?php \Doctrine\Common\Util\Debug::dump($query['options']) ?>
                </span>
                <span class="clear"></span>
            <?php endif ?>

            <?php if (isset($query['createCollection'])): ?>
                <span class="zdt-detail-label">Create collection</span>
                <span class="zdt-detail-value ddt-detail-value">
                    &nbsp;&nbsp;&nbsp;&nbsp;capped => <?php \Doctrine\Common\Util\Debug::dump($query['capped']) ?><br/>
                    &nbsp;&nbsp;&nbsp;&nbsp;size => <?php \Doctrine\Common\Util\Debug::dump($query['size']) ?><br/>
                    &nbsp;&nbsp;&nbsp;&nbsp;max => <?php \Doctrine\Common\Util\Debug::dump($query['max']) ?>
                </span>
                <span class="clear"></span>
            <?php endif ?>

            <?php if (isset($query['createDBRef'])): ?>
                <span class="zdt-detail-label">Create DB ref</span>
                <span class="zdt-detail-value ddt-detail-value">
                    &nbsp;&nbsp;&nbsp;&nbsp;collection => <?php \Doctrine\Common\Util\Debug::dump($query['collection']) ?><br/>
                    &nbsp;&nbsp;&nbsp;&nbsp;reference => <?php \Doctrine\Common\Util\Debug::dump($query['reference']) ?>
                </span>
                <span class="clear"></span>
            <?php endif ?>

            <?php if (isset($query['getDBRef'])): ?>
                <span class="zdt-detail-label">Get DB ref</span>
                <span class="zdt-detail-value ddt-detail-value">
                    &nbsp;&nbsp;&nbsp;&nbsp;reference => <?php \Doctrine\Common\Util\Debug::dump($query['reference']) ?>
                </span>
                <span class="clear"></span>
            <?php endif ?>

            <?php if (isset($query['drop'])): ?>
                <span class="zdt-detail-label">Drop database</span>
                <span class="zdt-detail-value ddt-detail-value">
                    &nbsp;&nbsp;&nbsp;&nbsp;dropDatabase => <?php \Doctrine\Common\Util\Debug::dump($query['dropDatabase']) ?>
                </span>
                <span class="clear"></span>
            <?php endif ?>

            <?php if (isset($query['execute'])): ?>
                <span class="zdt-detail-label">Code</span>
                <span class="zdt-detail-value ddt-detail-value">
                    <?php print_r($query['code']) ?>
                </span>
                <span class="clear"></span>
                <span class="zdt-detail-label">Args</span>
                <span class="zdt-detail-value ddt-detail-value">
                    <?php foreach($query['args'] as $key => $value): ?>
                        &nbsp;&nbsp;&nbsp;&nbsp;<?php echo $key ?> => <?php \Doctrine\Common\Util\Debug::dump($value) ?><br/>
                    <?php endforeach ?>
                </span>
                <span class="clear"></span>
            <?php endif ?>
        <?php endforeach ?>
        </span>
    </div>
</div>
<style>
.zdt-toolbar-entry .zdt-toolbar-detail .ddt-toolbar-info {

    font-size: 11px;
    max-width: 600px;
    witdh: 600px;
    max-height: 300px;
    overflow-y: scroll;
    overflow-x: hidden;
}

.zdt-toolbar-entry .zdt-toolbar-detail .ddt-detail-query {

    white-space: normal;
    width: 400px;
}

.zdt-toolbar-entry .zdt-toolbar-detail .ddt-detail-query .highlight {

    color: #80DC09;
    font-weight: bold;
}

.zdt-toolbar-entry .zdt-toolbar-info .clear {

    clear: both;
    display: block;
}

.zdt-toolbar-entry .zdt-toolbar-detail .ddt-toolbar-info hr {

    border: 0;
    border-top: 1px solid #80DC09;
    clear: both;
}
</style>
